## Introduction to Data Science: Regular Expression and Pandas

**Exercise #2 : Regex and Pandas **

In [31]:
#Import libraries
import os, csv 
import re

import pandas as pd

In [33]:
#Open the file "ca_sample_data_a.csv" in "read mode"

#We need to verify that the phone column is in the following format : ddd-ddd-dddd (where d is a digit) (i.e. 514-321-0909)
#We need to verify that the email column is in the following format : xxxxxxx@xxxxx.xxx (where x is an alphanumeric character)

records = []
bad_phone_recs = []
bad_email_recs = []
good_recs = []

regex_phone = '^(\\d{3}[-.]\\d{3}[-.]\\d{4})$'
regex_email = r'^[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z_+])*@(([0-9a-zA-Z][-\w]*\.)+[a-zA-Z]{2,9})$'


filename = 'ca_sample_data_a.csv'
path = os.getcwd()
filepath = path + '\\sourcedata\\' + filename
outpath = path + '\\output\\'


#print(filepath)
fh = open (filepath, mode = 'r')
freader = csv.reader(fh)
next(freader,None)
for rec in freader:
    first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3 = rec
    #print(rec)
    records.append(rec)
fh.close()

for rec in records:
    #print(rec[7])
    #print(rec[8])
    
    found_phone = re.search(regex_phone,rec[7])
    found_email = re.search(regex_email,rec[8])
    
    if not found_phone:
        bad_phone_recs.append(rec)
        print('Phone is bad:',rec[7])
        
    if not found_email:
        bad_email_recs.append(rec)
        print('Email is bad:', rec[8])

    if found_phone and found_email:
        good_recs.append(rec)

#All records found with a phone that does not follow the given format are written to a file : bad_phone_recs.csv
#All records found with an email that does not follow the given format are written to a file : bad_email_recs.csv

#All good records should be written to a file : good_recs.csv

header = ['first_name','last_name','company_name','address','city','province','postal','phone1','email','web','exam_1','exam_2','exam_3']

fhw = open(outpath + 'bad_phone_recs.csv',mode='w', newline='')
fwriter = csv.writer(fhw)
fwriter.writerow(header)
fwriter.writerows(bad_phone_recs)
fhw.close()

fhw = open(outpath + 'bad_email_recs.csv',mode='w', newline='')
fwriter = csv.writer(fhw)
fwriter.writerow(header)
fwriter.writerows(bad_email_recs)
fhw.close()

fhw = open(outpath + 'good_recs.csv',mode='w', newline='')
fwriter = csv.writer(fhw)
fwriter.writerow(header)
fwriter.writerows(good_recs)
fhw.close()

Phone is bad: 780-XXX-3619
Phone is bad: 519-790-8?60
Phone is bad: 250-.07-7698
Phone is bad: 306748-5721
Email is bad: vvandeberg@gmail?com
Phone is bad: 50.-327-7460
Phone is bad: 902p804-8543
Email is bad: loreen_griepentrog^aol.com
Phone is bad: 50l-573-8903
Email is bad: coral.brennick@brennick.
Email is bad: latonia#helander.com
Phone is bad: 780-799-64l8
Email is bad: ???@cox.net

In [35]:
# Open the good_recs.csv file and load it into a Pandas DataFrame (let the index by default)

path = os.getcwd()
filename = 'good_recs.csv'
filepath = path +  '\\output\\' + filename

fh = open(filepath,mode='r')
df = pd.read_csv(fh,skiprows=0)
#myframe = pd.DataFrame()

#2.1 Show the first 5 records using .head()
df.head(5)

,first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3
0,Francoise,Rautenstrauch,"Riebesell, H F Jr",2335 Canton Hwy #6,Windsor,ON,N8N 3N2,519-569-8399,francoise.rautenstrauch@rautenstrauch.com,http://www.riebesellhfjr.com,60,94,79
1,Kendra,Loud,Deloitte & Touche,6 Arch St #9757,Alcida,NB,E8J 2C4,506-363-1526,kloud@gmail.com,http://www.deloittetouche.com,57,50,90
2,Lourdes,Bauswell,Oklahoma Neon Inc,9547 Belmont Rd #21,Belleville,ON,K8P 1B3,613-903-7043,lourdes_bauswell@aol.com,http://www.oklahomaneoninc.com,90,95,64
3,Hannah,Edmison,M B A Paint Stores,73 Pittsford Victor Rd,Vancouver,BC,V5Z 3K2,604-334-3686,hannah@yahoo.com,http://www.mbapaintstores.com,96,95,82
4,Tom,Loeza,Sheraton Shreveport Hotel,447 Commercial St Se,LIle-Perrot,QC,J7V 4T4,514-487-6096,tom.loeza@gmail.com,http://www.sheratonshreveporthotel.com,84,79,51

In [37]:
#2.2 Show the last 10 records using .tail()
df.tail(10)

,first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3
477,Esteban,Plantenberg,Midwest Wheel Companies,78 E River,Surrey,BC,V4P 0C4,604-519-9547,esteban@cox.net,http://www.midwestwheelcompanies.com,98,99,57
478,Doretha,Wykle,"Lafave, E Joseph Iii",5106 N Laurel Park Dr,Kenora,ON,P9N 4E7,807-383-4855,doretha@yahoo.com,http://www.lafaveejosephiii.com,66,71,57
479,Dorsey,Neitzke,"Turley, Joseph M",9768 A Aven #112,Truro,NS,B2N 3P6,902-936-9426,dorsey_neitzke@hotmail.com,http://www.turleyjosephm.com,80,53,90
480,Amie,Okuniewski,Motion Industries Inc,24 Venice Rd,Pembroke,ON,K8A 8M7,613-686-9039,amie@yahoo.com,http://www.motionindustriesinc.com,54,69,75
481,Bulah,Berkoff,Balan Marketing Co,2497 Pennsylvania Ave,Strathroy,ON,N7G 3V5,519-309-5863,bulah.berkoff@cox.net,http://www.balanmarketingco.com,61,74,53
482,Erin,Delbosque,Curtiss Wright Corp,357 W Mount Royal Ave,Longueuil,QC,J4M 2A8,450-316-7813,erin@cox.net,http://www.curtisswrightcorp.com,57,97,67
483,Kassandra,Marushia,Phelps Tool & Die Co Inc,123 Euclid Ave #9396,Nanaimo,BC,V9R 1C9,250-646-6446,kassandra@gmail.com,http://www.phelpstooldiecoinc.com,89,57,88
484,Leslee,Matsuno,Factory Mattress Outlet,1251 E Main St #990,Quebec,QC,G1H 1A6,418-460-5773,leslee_matsuno@matsuno.org,http://www.factorymattressoutlet.com,62,77,99
485,Daniel,Dobler,Cosgroves N End Plbg & Hdwr Co,259 W 17th St #39,Beresford,NB,E8K 1B7,506-617-2607,ddobler@dobler.com,http://www.cosgrovesnendplbghdwrco.com,100,79,58
486,Antonio,Unruh,Mission Lincoln Properties,9 Route 38,Port Coquitlam,BC,V3C 2Z4,604-624-7690,antonio.unruh@hotmail.com,http://www.missionlincolnproperties.com,76,54,85

In [39]:
#2.3 Print the column names using a for loop and the .columns collection
i=1
for col in df.columns:
    print('column {} name :'.format(i),col)
    i=i+1

column 1 name : first_name
column 2 name : last_name
column 3 name : company_name
column 4 name : address
column 5 name : city
column 6 name : province
column 7 name : postal
column 8 name : phone1
column 9 name : email
column 10 name : web
column 11 name : exam_1
column 12 name : exam_2
column 13 name : exam_3

In [41]:
#2.4 Slice the DF and show records 1 to 5 (inclusive)
df[0:5]

,first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3
0,Francoise,Rautenstrauch,"Riebesell, H F Jr",2335 Canton Hwy #6,Windsor,ON,N8N 3N2,519-569-8399,francoise.rautenstrauch@rautenstrauch.com,http://www.riebesellhfjr.com,60,94,79
1,Kendra,Loud,Deloitte & Touche,6 Arch St #9757,Alcida,NB,E8J 2C4,506-363-1526,kloud@gmail.com,http://www.deloittetouche.com,57,50,90
2,Lourdes,Bauswell,Oklahoma Neon Inc,9547 Belmont Rd #21,Belleville,ON,K8P 1B3,613-903-7043,lourdes_bauswell@aol.com,http://www.oklahomaneoninc.com,90,95,64
3,Hannah,Edmison,M B A Paint Stores,73 Pittsford Victor Rd,Vancouver,BC,V5Z 3K2,604-334-3686,hannah@yahoo.com,http://www.mbapaintstores.com,96,95,82
4,Tom,Loeza,Sheraton Shreveport Hotel,447 Commercial St Se,LIle-Perrot,QC,J7V 4T4,514-487-6096,tom.loeza@gmail.com,http://www.sheratonshreveporthotel.com,84,79,51

In [43]:
#2.5 Show the record with index (5) (use .loc)
df.loc[5]

first_name                                   Queenie
last_name                                 Kramarczyk
company_name                Goeman Wood Products Inc
address                              47 Garfield Ave
city                                   Swift Current
province                                          SK
postal                                       S9H 4V2
phone1                                  306-421-5793
email              queenie.kramarczyk@kramarczyk.org
web             http://www.goemanwoodproductsinc.com
exam_1                                            50
exam_2                                            90
exam_3                                            62
Name: 5, dtype: object

In [45]:
#2.6 Using .loc, show first_name and last_name for record with index 1
df.loc[1,['first_name','last_name']]


#2.7 Using .loc show first_name and last_name for records with index 1 and 5
#2.8 Using .loc show the last_name for record with index 3
#2.9 Try the method .describe with the dataframe and obtain stats on the exams
#2.10 Using a boolean mask, show the students with an exam_1 mark of 75 or more

first_name    Kendra
last_name       Loud
Name: 1, dtype: object

In [47]:
#2.7 Using .loc show first_name and last_name for records with index 1 and 5
df.loc[[1,5],['first_name','last_name']]

  first_name   last_name
1     Kendra        Loud
5    Queenie  Kramarczyk

In [49]:
#2.8 Using .loc show the last_name for record with index 3
df.loc[3,'last_name']

'Edmison'

In [51]:
#2.9 Try the method .describe with the dataframe and obtain stats on the exams
df.describe()

           exam_1      exam_2      exam_3
count  487.000000  487.000000  487.000000
mean    75.125257   74.353183   73.827515
std     15.245546   14.922520   14.929844
min     50.000000   50.000000   50.000000
25%     62.000000   61.000000   60.000000
50%     76.000000   73.000000   73.000000
75%     88.000000   88.000000   87.000000
max    100.000000  100.000000  100.000000

In [53]:
#2.10 Using a boolean mask, show the students with an exam_1 mark of 75 or more
filter = df['exam_1']>=75
df[filter]

,first_name,last_name,company_name,address,city,province,postal,phone1,email,web,exam_1,exam_2,exam_3
2,Lourdes,Bauswell,Oklahoma Neon Inc,9547 Belmont Rd #21,Belleville,ON,K8P 1B3,613-903-7043,lourdes_bauswell@aol.com,http://www.oklahomaneoninc.com,90,95,64
3,Hannah,Edmison,M B A Paint Stores,73 Pittsford Victor Rd,Vancouver,BC,V5Z 3K2,604-334-3686,hannah@yahoo.com,http://www.mbapaintstores.com,96,95,82
4,Tom,Loeza,Sheraton Shreveport Hotel,447 Commercial St Se,LIle-Perrot,QC,J7V 4T4,514-487-6096,tom.loeza@gmail.com,http://www.sheratonshreveporthotel.com,84,79,51
7,Josefa,Opitz,Norman Gale Isuzu,136 W Grand Ave #3,Delhi,ON,N4B 1C4,519-788-7645,josefa.opitz@opitz.org,http://www.normangaleisuzu.com,83,51,57
8,Lea,Steinhaus,"James, Christopher Esq",80 Maplewood Dr #34,Bradford,ON,L3Z 2S4,905-618-8258,lsteinhaus@cox.net,http://www.jameschristopheresq.com,79,59,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,Esteban,Plantenberg,Midwest Wheel Companies,78 E River,Surrey,BC,V4P 0C4,604-519-9547,esteban@cox.net,http://www.midwestwheelcompanies.com,98,99,57
479,Dorsey,Neitzke,"Turley, Joseph M",9768 A Aven #112,Truro,NS,B2N 3P6,902-936-9426,dorsey_neitzke@hotmail.com,http://www.turleyjosephm.com,80,53,90
483,Kassandra,Marushia,Phelps Tool & Die Co Inc,123 Euclid Ave #9396,Nanaimo,BC,V9R 1C9,250-646-6446,kassandra@gmail.com,http://www.phelpstooldiecoinc.com,89,57,88
485,Daniel,Dobler,Cosgroves N End Plbg & Hdwr Co,259 W 17th St #39,Beresford,NB,E8K 1B7,506-617-2607,ddobler@dobler.com,http://www.cosgrovesnendplbghdwrco.com,100,79,58
486,Antonio,Unruh,Mission Lincoln Properties,9 Route 38,Port Coquitlam,BC,V3C 2Z4,604-624-7690,antonio.unruh@hotmail.com,http://www.missionlincolnproperties.com,76,54,85